### ISSUE TITLE
Need to catch broken pipe and restart the wrapper process

### ISSUE THREAD

**Issue by FlyingDiver** [FlyingDiver/Indigo-BMW-CD#8]
```
   BMW Connected Drive Error       Error in plugin execution ExecuteAction:

Traceback (most recent call last):
  File "plugin.py", line 335, in sendCommandAction
  File "plugin.py", line 151, in wrapper_write
IOError: (32, 'Broken pipe')
```

**Comment by FlyingDiver** [comment]
Fixed in current venv branch

**Comment by FlyingDiver** [comment]
No longer applicable to Python3 version.
